# Network config
audionet:
  audionet_name: TDANetBest
  audionet_config:
    out_channels: 128
    in_channels: 512
    num_blocks: 16
    upsampling_depth: 5
    enc_kernel_size: 4 # ms
    num_sources: 2

# Loss config
loss:
  train:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_snr
    config:
      pit_from: pw_mtx
      threshold_byloss: true
  val:
    loss_func: PITLossWrapper
    sdr_type: pairwise_neg_sisdr
    config:
      pit_from: pw_mtx
      threshold_byloss: false

# Training config
training:
  system: AudioLightningModule
  gpus: [0, ]
  parallel: ddp
  epochs: 500
  early_stop:
    monitor: val_loss/dataloader_idx_0
    mode: min
    patience: 30
    verbose: true
  SpeedAug: False
  log_freq: 100

# Optim config
optimizer:
  optim_name: adam
  lr: 0.001
  weight_decay: 0

# Sche config
scheduler:
  sche_name: ReduceLROnPlateau
  sche_config:
    patience: 15
    factor: 0.5

# Data config
datamodule:
  data_name: LRS2DataModule
  data_config:
    train_dir: DataPreProcess/LRS2mix/debug
    valid_dir: DataPreProcess/LRS2mix/debug
    test_dir: DataPreProcess/LRS2mix/tt
    n_src: 2
    sample_rate: 16000
    segment: 2.0
    normalize_audio: false
    batch_size: 32
    num_workers: 0
    pin_memory: true
    persistent_workers: false

exp:
  exp_name: RemoteReprod
  project: TDANet_lsr2
  offline: True

main_args:
  exp_dir: D:\Projects\pyprog\TDANet\pretrained\lsr2_4ms